# Generated by Django 3.1.3 on 2025-01-29 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('men', '0002_auto_20230502_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Автор статьи'),
            preserve_default=False,
        ),
    ]
