# Generated by Django 3.1.3 on 2025-01-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_men_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='men.men', verbose_name='Статья')),
            ],
            options={
                'ordering': ['time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['time_create'], name='men_comment_time_cr_cdb5b6_idx'),
        ),
    ]
