# Generated by Django 5.0 on 2025-02-03 11:16

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0004_auto_20250130_1332'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='men',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
